# server: ./start-trackers.js 
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
browserify:
  - transform: babelify
    global: true
    presets: ['@babel/preset-env']